"""sprint 3 - identidade uuid e dados reais

Adapta o esquema aos dados reais (docs/DECISIONS.md, seção 13):
- Identidade UUID interna (String 36) como PK de todas as entidades;
  FKs convertidas em conjunto. Exceção documentada: `ufs.sigla`.
- Novas tabelas: tipos_promotor (cadastral, com seed TECNICO/TRADE),
  clientes_integracao, visitas_resumo_sb, carteiras_avert,
  visitas_produtos_sb, clientes_vendedores.
- Colunas novas/nulabilidades exigidas pelas fontes reais (clientes,
  visitas, checklists, faturamentos, promotores, importacoes,
  laboratorios).

Nota: linhas pré-existentes preservam o id numérico como texto ao migrar
(a POC não tem base em produção); linhas novas recebem UUID v4 via ORM.

Revision ID: 7a8767356031
Revises: 60b07303d82d
Create Date: 2026-07-12 11:14:33.575381

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a8767356031"
down_revision: str | Sequence[str] | None = "60b07303d82d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Seed cadastral dos tipos de promotor (docs/DECISIONS.md, seção 12: o tipo
# é cadastral e nunca inferido dos dados importados).
_TIPOS_PROMOTOR_SEED = [
    {"codigo": "TECNICO", "nome": "Promotor Técnico"},
    {"codigo": "TRADE", "nome": "Promotor Trade"},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipos_promotor",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.bulk_insert(
        sa.table(
            "tipos_promotor",
            sa.column("id", sa.String(length=36)),
            sa.column("codigo", sa.String(length=30)),
            sa.column("nome", sa.String(length=100)),
            sa.column("ativo", sa.Boolean()),
        ),
        [{"id": str(uuid.uuid4()), "ativo": True, **tipo} for tipo in _TIPOS_PROMOTOR_SEED],
    )
    op.create_table(
        "carteiras_avert",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cnpj", sa.String(length=20), nullable=False),
        sa.Column("cliente_id", sa.String(length=36), nullable=True),
        sa.Column("promotor_id", sa.String(length=36), nullable=True),
        sa.Column("competencia", sa.Date(), nullable=True),
        sa.Column("uf_sigla", sa.String(length=2), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("regional", sa.String(length=100), nullable=True),
        sa.Column("distribuidor", sa.String(length=150), nullable=True),
        sa.Column("coordenador", sa.String(length=150), nullable=True),
        sa.Column("consultor", sa.String(length=150), nullable=True),
        sa.Column("vendedor", sa.String(length=150), nullable=True),
        sa.Column("grupo_economico", sa.String(length=150), nullable=True),
        sa.Column("nome_fantasia", sa.String(length=200), nullable=True),
        sa.Column("razao_social", sa.String(length=200), nullable=True),
        sa.Column("segmento", sa.String(length=100), nullable=True),
        sa.Column("compra_2025", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("compra_2026", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("crescimento", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("importacao_id", sa.String(length=36), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["promotor_id"], ["promotores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uf_sigla"], ["ufs.sigla"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("carteiras_avert", schema=None) as batch_op:
        batch_op.create_index("ix_carteiras_avert_cnpj", ["cnpj"], unique=False)

    op.create_table(
        "clientes_integracao",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "sistema_origem",
            sa.Enum(
                "SB_PROMOTOR",
                "WECHECK",
                "PAINEL_AVERT",
                name="sistemaorigem",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("codigo_origem", sa.String(length=255), nullable=False),
        sa.Column("nome_origem", sa.String(length=255), nullable=True),
        sa.Column("cliente_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE",
                "VINCULADO",
                "IGNORADO",
                name="statusconciliacao",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("observacao", sa.String(length=255), nullable=True),
        sa.Column("importacao_id", sa.String(length=36), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sistema_origem", "codigo_origem", name="uq_clientes_integracao_origem_codigo"
        ),
    )
    op.create_table(
        "clientes_vendedores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cliente_id", sa.String(length=36), nullable=False),
        sa.Column("vendedor_id", sa.String(length=36), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("importacao_id", sa.String(length=36), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vendedor_id"], ["vendedores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cliente_id", "ordem", name="uq_clientes_vendedores_cliente_ordem"),
    )
    op.create_table(
        "visitas_produtos_sb",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("codigo_visita_externa", sa.String(length=50), nullable=False),
        sa.Column("promotor_id", sa.String(length=36), nullable=False),
        sa.Column("cliente_id", sa.String(length=36), nullable=False),
        sa.Column("uf_sigla", sa.String(length=2), nullable=True),
        sa.Column("data_inicial", sa.Date(), nullable=True),
        sa.Column("data_final", sa.Date(), nullable=True),
        sa.Column("operacao", sa.String(length=50), nullable=True),
        sa.Column("grupo_marca", sa.String(length=100), nullable=True),
        sa.Column("marca", sa.String(length=100), nullable=True),
        sa.Column("codigo_produto", sa.String(length=50), nullable=True),
        sa.Column("produto", sa.String(length=255), nullable=True),
        sa.Column("validade", sa.Date(), nullable=True),
        sa.Column("lote", sa.String(length=50), nullable=True),
        sa.Column("estoque", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("preco", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("importacao_id", sa.String(length=36), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["promotor_id"], ["promotores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uf_sigla"], ["ufs.sigla"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("visitas_produtos_sb", schema=None) as batch_op:
        batch_op.create_index(
            "ix_visitas_produtos_sb_visita", ["codigo_visita_externa"], unique=False
        )

    op.create_table(
        "visitas_resumo_sb",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("promotor_id", sa.String(length=36), nullable=False),
        sa.Column("cliente_id", sa.String(length=36), nullable=False),
        sa.Column("competencia", sa.Date(), nullable=False),
        sa.Column("visitas_previstas", sa.Integer(), nullable=True),
        sa.Column("previstas_realizadas", sa.Integer(), nullable=True),
        sa.Column("previstas_nao_realizadas", sa.Integer(), nullable=True),
        sa.Column("nao_previstas_realizadas", sa.Integer(), nullable=True),
        sa.Column("cliente_visitas_previstas", sa.Integer(), nullable=True),
        sa.Column("cliente_visitas_realizadas", sa.Integer(), nullable=True),
        sa.Column("cliente_nao_visitas", sa.Integer(), nullable=True),
        sa.Column("perc_visitas_realizadas", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("perc_nao_visitas", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("perc_cobertura", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("importacao_id", sa.String(length=36), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["promotor_id"], ["promotores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "promotor_id",
            "cliente_id",
            "competencia",
            name="uq_visitas_resumo_sb_promotor_cliente_competencia",
        ),
    )
    with op.batch_alter_table("carteiras", schema=None) as batch_op:
        batch_op.add_column(sa.Column("competencia", sa.Date(), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "promotor_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cliente_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("checklist_perguntas", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "checklist_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("checklist_respostas", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "visita_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checklist_pergunta_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "resposta_valor",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.Text(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("checklists", schema=None) as batch_op:
        batch_op.add_column(sa.Column("codigo_externo", sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column(
                "origem",
                sa.Enum(
                    "SB_PROMOTOR",
                    "WECHECK",
                    "PAINEL_AVERT",
                    name="sistemaorigem",
                    native_enum=False,
                    length=20,
                ),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "tipo_promotor_alvo", existing_type=sa.VARCHAR(length=20), nullable=True
        )
        batch_op.create_unique_constraint(
            "uq_checklists_origem_codigo", ["origem", "codigo_externo"]
        )

    with op.batch_alter_table("cidades", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )

    with op.batch_alter_table("clientes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("inscricao_estadual", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("tipo_pessoa", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("ramo_atividade", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("numero", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("bairro", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("cep", sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column("telefone", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("data_ultima_compra", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "cidade_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("departamentos", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )

    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "criado_por",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "atualizado_por",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.drop_column("uuid")

    with op.batch_alter_table("faturamentos", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "cliente_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "laboratorio_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "departamento_id", existing_type=sa.INTEGER(), type_=sa.String(length=36), nullable=True
        )
        batch_op.alter_column(
            "vendedor_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("importacao_arquivos", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("importacao_erros", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("importacoes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hash_conteudo", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("competencia", sa.Date(), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "usuario_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "importacao_pai_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.create_index("ix_importacoes_hash_conteudo", ["hash_conteudo"], unique=False)

    with op.batch_alter_table("laboratorios", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "categoria",
                sa.Enum(
                    "LABORATORIO", "BRINDE", name="categoriacomercial", native_enum=False, length=20
                ),
                server_default="LABORATORIO",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )

    with op.batch_alter_table("logs_auditoria", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "entidade_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "usuario_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )

    with op.batch_alter_table("promotores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tipo_promotor_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("area", sa.String(length=100), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "supervisor_id", existing_type=sa.INTEGER(), type_=sa.String(length=36), nullable=True
        )

    # Migra o enum embutido para a tabela cadastral antes de descartá-lo.
    op.execute(
        "UPDATE promotores SET tipo_promotor_id = "
        "(SELECT id FROM tipos_promotor WHERE tipos_promotor.codigo = promotores.tipo)"
    )

    with op.batch_alter_table("promotores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promotores_tipo"))
        batch_op.create_index("ix_promotores_tipo", ["tipo_promotor_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_promotores_tipo_promotor_id",
            "tipos_promotor",
            ["tipo_promotor_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("tipo")

    with op.batch_alter_table("supervisores", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )

    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "promotor_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "supervisor_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )

    with op.batch_alter_table("vendedores", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )

    with op.batch_alter_table("visitas", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "origem",
                sa.Enum(
                    "SB_PROMOTOR",
                    "WECHECK",
                    "PAINEL_AVERT",
                    name="sistemaorigem",
                    native_enum=False,
                    length=20,
                ),
                server_default="SB_PROMOTOR",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("codigo_externo", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("cliente_integracao_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("local_texto", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("endereco_texto", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("cidade_texto", sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column("estado_texto", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("dados_brutos", sa.JSON(), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False
        )
        batch_op.alter_column(
            "promotor_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cliente_id", existing_type=sa.INTEGER(), type_=sa.String(length=36), nullable=True
        )
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint("uq_visitas_origem_codigo", ["origem", "codigo_externo"])
        batch_op.create_foreign_key(
            "fk_visitas_cliente_integracao_id",
            "clientes_integracao",
            ["cliente_integracao_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitas", schema=None) as batch_op:
        batch_op.drop_constraint("fk_visitas_cliente_integracao_id", type_="foreignkey")
        batch_op.drop_constraint("uq_visitas_origem_codigo", type_="unique")
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cliente_id", existing_type=sa.String(length=36), type_=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "promotor_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("dados_brutos")
        batch_op.drop_column("estado_texto")
        batch_op.drop_column("cidade_texto")
        batch_op.drop_column("endereco_texto")
        batch_op.drop_column("local_texto")
        batch_op.drop_column("cliente_integracao_id")
        batch_op.drop_column("codigo_externo")
        batch_op.drop_column("origem")

    with op.batch_alter_table("vendedores", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.alter_column(
            "supervisor_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "promotor_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("supervisores", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    # Restaura o enum embutido a partir da tabela cadastral antes de removê-la.
    with op.batch_alter_table("promotores", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tipo", sa.VARCHAR(length=20), server_default="TRADE", nullable=False)
        )
    op.execute(
        "UPDATE promotores SET tipo = COALESCE("
        "(SELECT codigo FROM tipos_promotor WHERE tipos_promotor.id = promotores.tipo_promotor_id),"
        " 'TRADE')"
    )
    with op.batch_alter_table("promotores", schema=None) as batch_op:
        batch_op.alter_column("tipo", server_default=None, existing_type=sa.VARCHAR(length=20))
        batch_op.drop_constraint("fk_promotores_tipo_promotor_id", type_="foreignkey")
        batch_op.drop_index("ix_promotores_tipo")
        batch_op.create_index(batch_op.f("ix_promotores_tipo"), ["tipo"], unique=False)
        batch_op.alter_column(
            "supervisor_id", existing_type=sa.String(length=36), type_=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("area")
        batch_op.drop_column("tipo_promotor_id")

    with op.batch_alter_table("logs_auditoria", schema=None) as batch_op:
        batch_op.alter_column(
            "usuario_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "entidade_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("laboratorios", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("categoria")

    with op.batch_alter_table("importacoes", schema=None) as batch_op:
        batch_op.drop_index("ix_importacoes_hash_conteudo")
        batch_op.alter_column(
            "importacao_pai_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "usuario_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("competencia")
        batch_op.drop_column("hash_conteudo")

    with op.batch_alter_table("importacao_erros", schema=None) as batch_op:
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("importacao_arquivos", schema=None) as batch_op:
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("faturamentos", schema=None) as batch_op:
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "vendedor_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "departamento_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            nullable=False,
        )
        batch_op.alter_column(
            "laboratorio_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cliente_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    # `uuid` volta como coluna própria; linhas existentes recebem o valor do
    # id (que na ida foi consolidado a partir dela ou já era UUID).
    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.VARCHAR(length=36), nullable=True))
    op.execute("UPDATE empresas SET uuid = id")
    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.alter_column("uuid", existing_type=sa.VARCHAR(length=36), nullable=False)
        batch_op.create_unique_constraint("uq_empresas_uuid", ["uuid"])
        batch_op.alter_column(
            "atualizado_por",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "criado_por",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("departamentos", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("clientes", schema=None) as batch_op:
        batch_op.alter_column(
            "cidade_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("data_ultima_compra")
        batch_op.drop_column("telefone")
        batch_op.drop_column("cep")
        batch_op.drop_column("bairro")
        batch_op.drop_column("numero")
        batch_op.drop_column("ramo_atividade")
        batch_op.drop_column("tipo_pessoa")
        batch_op.drop_column("inscricao_estadual")

    with op.batch_alter_table("cidades", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("checklists", schema=None) as batch_op:
        batch_op.drop_constraint("uq_checklists_origem_codigo", type_="unique")
        batch_op.alter_column(
            "tipo_promotor_alvo", existing_type=sa.VARCHAR(length=20), nullable=False
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("origem")
        batch_op.drop_column("codigo_externo")

    with op.batch_alter_table("checklist_respostas", schema=None) as batch_op:
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "resposta_valor",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=500),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checklist_pergunta_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "visita_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("checklist_perguntas", schema=None) as batch_op:
        batch_op.alter_column(
            "checklist_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("carteiras", schema=None) as batch_op:
        batch_op.alter_column(
            "importacao_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cliente_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "promotor_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(length=36), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.drop_column("competencia")

    op.drop_table("visitas_resumo_sb")
    with op.batch_alter_table("visitas_produtos_sb", schema=None) as batch_op:
        batch_op.drop_index("ix_visitas_produtos_sb_visita")

    op.drop_table("visitas_produtos_sb")
    op.drop_table("clientes_vendedores")
    op.drop_table("clientes_integracao")
    with op.batch_alter_table("carteiras_avert", schema=None) as batch_op:
        batch_op.drop_index("ix_carteiras_avert_cnpj")

    op.drop_table("carteiras_avert")
    op.drop_table("tipos_promotor")
    # ### end Alembic commands ###
