"""modelagem inicial completa

Revision ID: f6da2ac2c23c
Revises:
Create Date: 2026-07-09 23:43:41.978420

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6da2ac2c23c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column(
            "tipo_promotor_alvo",
            sa.Enum(
                "TECNICO", "TRADE", "AMBOS", name="tipopromotoralvo", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "departamentos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("codigo_externo", sa.String(length=50), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_externo"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "laboratorios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("codigo_externo", sa.String(length=50), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_externo"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "supervisores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("codigo_externo", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_externo"),
    )
    op.create_table(
        "ufs",
        sa.Column("sigla", sa.String(length=2), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("regiao", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("sigla"),
    )
    op.create_table(
        "vendedores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("codigo_externo", sa.String(length=50), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_externo"),
    )
    op.create_table(
        "checklist_perguntas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("checklist_id", sa.Integer(), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("enunciado", sa.String(length=500), nullable=False),
        sa.Column(
            "tipo_resposta",
            sa.Enum(
                "SIM_NAO",
                "MULTIPLA_ESCOLHA",
                "NUMERICO",
                "TEXTO",
                name="tiporespostachecklist",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("obrigatoria", sa.Boolean(), nullable=False),
        sa.Column("peso", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["checklist_id"], ["checklists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checklist_id", "ordem", name="uq_checklist_perguntas_checklist_ordem"),
    )
    op.create_table(
        "cidades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("uf_sigla", sa.String(length=2), nullable=False),
        sa.Column("codigo_ibge", sa.String(length=10), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uf_sigla"], ["ufs.sigla"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_ibge"),
        sa.UniqueConstraint("nome", "uf_sigla", name="uq_cidades_nome_uf"),
    )
    op.create_table(
        "promotores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("codigo_externo", sa.String(length=50), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum("TECNICO", "TRADE", name="tipopromotor", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("supervisor_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("data_admissao", sa.Date(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["supervisor_id"], ["supervisores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_externo"),
    )
    op.create_index("ix_promotores_tipo", "promotores", ["tipo"], unique=False)
    op.create_table(
        "clientes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo_externo", sa.String(length=50), nullable=False),
        sa.Column("razao_social", sa.String(length=200), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=200), nullable=True),
        sa.Column("cnpj_cpf", sa.String(length=20), nullable=True),
        sa.Column("uf_sigla", sa.String(length=2), nullable=False),
        sa.Column("cidade_id", sa.Integer(), nullable=False),
        sa.Column("endereco", sa.String(length=255), nullable=True),
        sa.Column("canal", sa.String(length=50), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cidade_id"], ["cidades.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uf_sigla"], ["ufs.sigla"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_externo"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "perfil",
            sa.Enum(
                "ADMINISTRADOR",
                "SUPERVISOR",
                "PROMOTOR",
                "DIRETORIA",
                name="perfilusuario",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("promotor_id", sa.Integer(), nullable=True),
        sa.Column("supervisor_id", sa.Integer(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ultimo_login_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["promotor_id"], ["promotores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supervisor_id"], ["supervisores.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("promotor_id"),
        sa.UniqueConstraint("supervisor_id"),
    )
    op.create_table(
        "importacoes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "tipo_arquivo",
            sa.Enum(
                "CLIENTES",
                "CARTEIRA",
                "FATURAMENTO",
                "CHECKLIST",
                "VISITAS",
                name="tipoarquivoimportacao",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("nome_arquivo_original", sa.String(length=255), nullable=False),
        sa.Column("hash_sha256", sa.String(length=64), nullable=False),
        sa.Column("tamanho_bytes", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE",
                "PROCESSANDO",
                "CONCLUIDA",
                "CONCLUIDA_COM_ERROS",
                "FALHOU",
                "REVERTIDA",
                name="statusimportacao",
                native_enum=False,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("importacao_pai_id", sa.Integer(), nullable=True),
        sa.Column("total_linhas", sa.Integer(), nullable=False),
        sa.Column("linhas_validas", sa.Integer(), nullable=False),
        sa.Column("linhas_invalidas", sa.Integer(), nullable=False),
        sa.Column("iniciado_em", sa.DateTime(), nullable=True),
        sa.Column("concluido_em", sa.DateTime(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["importacao_pai_id"], ["importacoes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_importacoes_hash", "importacoes", ["hash_sha256"], unique=False)
    op.create_index(
        "ix_importacoes_tipo_versao", "importacoes", ["tipo_arquivo", "versao"], unique=False
    )
    op.create_table(
        "logs_auditoria",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entidade", sa.String(length=100), nullable=False),
        sa.Column("entidade_id", sa.Integer(), nullable=True),
        sa.Column(
            "acao",
            sa.Enum(
                "CRIACAO",
                "ATUALIZACAO",
                "EXCLUSAO",
                "IMPORTACAO",
                "LOGIN",
                "LOGOUT",
                "ROLLBACK",
                "EXPORTACAO",
                name="acaoauditoria",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("dados_antes", sa.JSON(), nullable=True),
        sa.Column("dados_depois", sa.JSON(), nullable=True),
        sa.Column("ip_origem", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_logs_auditoria_entidade", "logs_auditoria", ["entidade", "entidade_id"], unique=False
    )
    op.create_index("ix_logs_auditoria_usuario", "logs_auditoria", ["usuario_id"], unique=False)
    op.create_table(
        "carteiras",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("promotor_id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column("data_inicio_vigencia", sa.Date(), nullable=False),
        sa.Column("data_fim_vigencia", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ATIVA", "ENCERRADA", name="statuscarteira", native_enum=False, length=15),
            nullable=False,
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["promotor_id"], ["promotores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_carteiras_cliente_vigencia",
        "carteiras",
        ["cliente_id", "data_fim_vigencia"],
        unique=False,
    )
    op.create_table(
        "faturamentos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("laboratorio_id", sa.Integer(), nullable=False),
        sa.Column("departamento_id", sa.Integer(), nullable=False),
        sa.Column("vendedor_id", sa.Integer(), nullable=True),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.Column("valor_faturado", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("quantidade", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["departamento_id"], ["departamentos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["laboratorio_id"], ["laboratorios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vendedor_id"], ["vendedores.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_faturamentos_cliente_periodo",
        "faturamentos",
        ["cliente_id", "ano", "mes"],
        unique=False,
    )
    op.create_index("ix_faturamentos_periodo", "faturamentos", ["ano", "mes"], unique=False)
    op.create_table(
        "importacao_arquivos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column("caminho_armazenamento", sa.String(length=500), nullable=False),
        sa.Column("nome_arquivo", sa.String(length=255), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("importacao_id"),
    )
    op.create_table(
        "importacao_erros",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column("numero_linha", sa.Integer(), nullable=False),
        sa.Column("coluna", sa.String(length=100), nullable=True),
        sa.Column("valor_recebido", sa.String(length=500), nullable=True),
        sa.Column("mensagem_erro", sa.String(length=500), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visitas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("promotor_id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("data_visita", sa.Date(), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=True),
        sa.Column("hora_fim", sa.Time(), nullable=True),
        sa.Column("tipo_visita", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "REALIZADA",
                "CANCELADA",
                "PENDENTE",
                name="statusvisita",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["promotor_id"], ["promotores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_visitas_promotor_data", "visitas", ["promotor_id", "data_visita"], unique=False
    )
    op.create_table(
        "checklist_respostas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("visita_id", sa.Integer(), nullable=False),
        sa.Column("checklist_pergunta_id", sa.Integer(), nullable=False),
        sa.Column("resposta_valor", sa.String(length=500), nullable=False),
        sa.Column("conforme", sa.Boolean(), nullable=True),
        sa.Column("importacao_id", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checklist_pergunta_id"], ["checklist_perguntas.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["importacao_id"], ["importacoes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["visita_id"], ["visitas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "visita_id", "checklist_pergunta_id", name="uq_checklist_respostas_visita_pergunta"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checklist_respostas")
    op.drop_index("ix_visitas_promotor_data", table_name="visitas")
    op.drop_table("visitas")
    op.drop_table("importacao_erros")
    op.drop_table("importacao_arquivos")
    op.drop_index("ix_faturamentos_periodo", table_name="faturamentos")
    op.drop_index("ix_faturamentos_cliente_periodo", table_name="faturamentos")
    op.drop_table("faturamentos")
    op.drop_index("ix_carteiras_cliente_vigencia", table_name="carteiras")
    op.drop_table("carteiras")
    op.drop_index("ix_logs_auditoria_usuario", table_name="logs_auditoria")
    op.drop_index("ix_logs_auditoria_entidade", table_name="logs_auditoria")
    op.drop_table("logs_auditoria")
    op.drop_index("ix_importacoes_tipo_versao", table_name="importacoes")
    op.drop_index("ix_importacoes_hash", table_name="importacoes")
    op.drop_table("importacoes")
    op.drop_table("usuarios")
    op.drop_table("clientes")
    op.drop_index("ix_promotores_tipo", table_name="promotores")
    op.drop_table("promotores")
    op.drop_table("cidades")
    op.drop_table("checklist_perguntas")
    op.drop_table("vendedores")
    op.drop_table("ufs")
    op.drop_table("supervisores")
    op.drop_table("laboratorios")
    op.drop_table("departamentos")
    op.drop_table("checklists")
    # ### end Alembic commands ###
